# DW Spectrum Multi-Monitor Launcher
# Auto-generated by DW Spectrum Installer

# Configuration
$dwSpectrumPath = "C:\Program Files\Digital Watchdog\DW Spectrum\Client\6.0.6.41837\DW Spectrum Launcher.exe"
$serverIP = "108.58.100.59"
$serverPort = "5623"
$username = "Sholam"
$password = "Sholam@B&H"

# Layout names
$monitor1Layout = "Monitor 1"
$monitor2Layout = "Monitor 2"

# Verify DW Spectrum is installed
if (-not (Test-Path $dwSpectrumPath)) {
    Write-Host "ERROR: DW Spectrum not found at: $dwSpectrumPath" -ForegroundColor Red
    Write-Host "Please verify the installation path and update the script." -ForegroundColor Yellow
    pause
    exit
}

Write-Host "Launching DW Spectrum on 2 monitor(s)..." -ForegroundColor Green
Write-Host "Server: $serverIP`:$serverPort" -ForegroundColor Cyan
Write-Host ""

# Build authentication string (URL encode special characters in password)
$encodedPassword = $password -replace '@', '%40' -replace '&', '%26'
$authString = "http://${username}:${encodedPassword}@${serverIP}:${serverPort}"

# Launch Monitor 1 (Screen 0)
Write-Host "Starting Monitor 1..." -ForegroundColor Yellow

# Try to launch with the specified layout name
# If the layout doesn't exist, DW Spectrum will open with a blank/default view
# The user can then arrange cameras and save the layout with the correct name

$arguments1 = @(
    "--no-single-application",
    "--auth=$authString",
    "--screen=0",
    "--no-client-update"
)

# Add layout name parameter if it's specified and not empty
if (-not [string]::IsNullOrWhiteSpace($monitor1Layout)) {
    $arguments1 += "--layout-name=`"$monitor1Layout`""
    Write-Host "  Layout: $monitor1Layout" -ForegroundColor Gray
} else {
    Write-Host "  No layout specified - opening blank window" -ForegroundColor Yellow
}

Start-Process -FilePath $dwSpectrumPath -ArgumentList $arguments1
# Wait before launching next instance
Start-Sleep -Seconds 2

# Launch Monitor 2 (Screen 1)
Write-Host "Starting Monitor 2..." -ForegroundColor Yellow

# Try to launch with the specified layout name
# If the layout doesn't exist, DW Spectrum will open with a blank/default view
# The user can then arrange cameras and save the layout with the correct name

$arguments2 = @(
    "--no-single-application",
    "--auth=$authString",
    "--screen=1",
    "--no-client-update"
)

# Add layout name parameter if it's specified and not empty
if (-not [string]::IsNullOrWhiteSpace($monitor2Layout)) {
    $arguments2 += "--layout-name=`"$monitor2Layout`""
    Write-Host "  Layout: $monitor2Layout" -ForegroundColor Gray
} else {
    Write-Host "  No layout specified - opening blank window" -ForegroundColor Yellow
}

Start-Process -FilePath $dwSpectrumPath -ArgumentList $arguments2

Write-Host ""
Write-Host "All instances launched successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "FIRST TIME SETUP INSTRUCTIONS" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "If your layouts don't appear (blank windows):" -ForegroundColor Yellow
Write-Host "  1. Arrange cameras in each window as desired" -ForegroundColor White
Write-Host "  2. Click Main Menu (top-left hamburger icon)" -ForegroundColor White
Write-Host "  3. Select 'Save Windows Configuration'" -ForegroundColor White
Write-Host "  4. Enter the layout name EXACTLY as specified:" -ForegroundColor White
Write-Host "     Monitor 1: Monitor 1" -ForegroundColor Cyan
Write-Host "     Monitor 2: Monitor 2" -ForegroundColor Cyan
Write-Host ""
Write-Host "  5. Click Save" -ForegroundColor White
Write-Host "  6. Repeat for each monitor" -ForegroundColor White
Write-Host ""
Write-Host "Next time you run this launcher, your layouts will load automatically!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
